Added PN Counter schema
erosb/hz-yaml-config-schema pull request #10
Opened 2020-10-21 00:19 UTC by yuraku

- added `pn counter` schema

2020-10-21 15:59 UTC, erosb requested changes
Thanks for the PR, added a couple of minor comments. Please let me know @yuraku if you won't have time to address them.

2020-10-21 15:59 UTC, erosb commented on src/main/resources/hazelcast-config-schema.json
> +        "max-concurrent-replication-targets": {
Please add `"default":1` here (according to CRDTReplicationConfig.java)

2020-10-21 15:59 UTC, erosb commented on src/main/resources/hazelcast-config-schema.json
> +        "replication-period-millis": {
The default is 1000 here (same source file)

2020-10-21 15:59 UTC, erosb commented on src/main/resources/hazelcast-config-schema.json
> +          "minLength": 1,
I think it can be deleted (`"minLength"` is only applicable to string instances)

2020-10-21 15:59 UTC, erosb commented on src/main/resources/hazelcast-config-schema.json
> +          "description": "The maximum number of target members that we replicate the CRDT states to in one period.",
Please add the whole description from full-example yaml (it isn't a problem if it becomes a very long line).

2020-10-21 15:59 UTC, erosb commented on src/main/resources/hazelcast-config-schema.json
> +          "description": "The period between two replications of CRDT states in milliseconds.",
Same comment here about the description.

2020-10-22 12:16 UTC, yuraku commented
hey @erosb. I've updated code based on the comments, pls take a look on it when you have time

2020-10-26 08:24 UTC, erosb approved these changes
Looks good now, thanks for the updates.

2020-10-26 08:28 UTC, merged